version: '3'

services:
  # PostgreSQL
  db:
    image: postgres:13
    container_name: telegram_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./telegram_posts.sql:/docker-entrypoint-initdb.d/telegram_posts.sql  # Монтируем скрипт создания таблицы telegram_posts
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_username -d your_dbname"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

  # telegram_script
  telegram_script:
    build: .
    container_name: telegram_script
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 100m

# Том для хранения данных PostgreSQL
volumes:
  postgres_data: